<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{1b25311b-b9b7-4ec0-ae90-6b6dc302e5fd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	SerialComm	: FB_EL6001;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>